"""empty message

Revision ID: 597cd7920446
Revises: 73b6772f2f9b
Create Date: 2020-12-20 02:16:29.031536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597cd7920446'
down_revision = '73b6772f2f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_venue_id_fkey', 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
